#pragma once

#define PLAYER_SIZE 20
#define GRID_CELL_SIZE 25
#define SCREEN_WIDTH 800
#define SCREEN_HEIGHT 800
#define NUMBER_OF_CELLS_X (SCREEN_WIDTH / GRID_CELL_SIZE - 1)
#define NUMBER_OF_CELLS_Y (SCREEN_HEIGHT / GRID_CELL_SIZE - 1)
